input_path:
  charges: ./Data/Charges_use.csv
  damages: ./Data/Damages_use.csv
  endorse: ./Data/Endorse_use.csv
  primary_person: ./Data/Primary_Person_use.csv
  restricts: ./Data/Restrict_use.csv
  units: ./Data/Units_use.csv

output_path:
  path1: ./Output/Analytics1
  path2: ./Output/Analytics2
  path3: ./Output/Analytics3
  path4: ./Output/Analytics4
  path5: ./Output/Analytics5
  path6: ./Output/Analytics6
  path7: ./Output/Analytics7
  path8: ./Output/Analytics8
